include:
  - project: 'mamis/gitlab-templates'
    ref: v1.13.2
    file: 'gitlab-ci-includes/php-lint.gitlab-ci.yml'

stages:
  - lint

php-lint:
  extends: .php-lint
  stage: lint
  image:
    name: registry.mamis.com.au/mamis/containers/php/build:${PHP_VERSION}
    entrypoint: ["/docker-entrypoint.sh"]
  parallel:
    matrix:
      - PHP_VERSION:
        - '7.0'
        - '7.1'
        - '7.2'
        - '7.3'
        - '7.4'
        - '8.0'
        - '8.1'
        - '8.2'
  before_script:
    - composer require --quiet --no-interaction php-parallel-lint/php-parallel-lint
    - !reference [.php-lint, before_script]

php-phpcs:
  stage: lint
  image:
    name: registry.mamis.com.au/mamis/containers/php/build:8.2
    entrypoint: ["/docker-entrypoint.sh"]
  before_script:
    - composer require --quiet --no-interaction squizlabs/php_codesniffer
    - php --version
    - ./vendor/bin/phpcs --version
    - ./vendor/bin/phpcs --colors --standard=PSR2 --report=full .
    - ./vendor/bin/phpcs --colors --standard=PSR2 --report=summary .
    - ./vendor/bin/phpcs --colors --standard=PSR2 --report=gitblame .
  script:
    - ./vendor/bin/phpcs
  allow_failure: true
